unique_ids:
  assets:
    standard-page.html: HA6NRESOB37OI4FX3CZAGS5QR277RY3E
    theme.css: 67V4J4VS24I2SYMW5AY7GY4CUZCJY37I
  forms:
    Form1: S7ZSFMLCB5I6GA66YPC7S65EXDPP4DW5
  modules: {}
  scripts: {}
  server_modules:
    api_endpoints: GIZOFVWID5IBFQMZY7AH2RMCJNBLWHS6
    examples: D764QZQVTGC4S4WYKN5XICUIODAUKUYA
    facts: C7CVCYWPO4N25A2VGSX42WUXREPXRAFV
    generation: 3OSSK2TFVC6XCI2MBOVSFE4GAJQ4S42Z
    prompts: PSJVJHT6D7UW7SY4C2FEKVPDFIUD3XBZ
    retrieval: 7LTG6QK3NRNKX6WTEHHLE3XEKGJXIILA
    utils: K6WNTGBGXSZMTXZVRK7DUFR6WJVR4TAG
